---@class SelectionRange
---@field start_line integer  1-indexed start line of the selection.
---@field end_line integer    1-indexed end line of the selection.
---@field start_col integer   1-indexed start column of the selection.
---@field end_col integer     1-indexed end column of the selection.

---@class AgentContext
---Plain data bag passed to the agent alongside the prompt.
---@field filename string        Path of the source file being edited.
---@field temp_dir string        Directory where temporary files are written.
---@field temp_file string       Path of the temp file the agent should write its output to (set by Agent:run).
---@field model string           Model identifier to use for this run.
---@field selection string       The text selected by the user.
---@field buffer string          Full contents of the source buffer at the time of invocation.
---@field range SelectionRange   Line/column range of the selection in the source buffer.
---@field user_prompt string     The raw prompt entered by the user.

---@class AgentProvider
---@field get_provider_name fun(self: AgentProvider): string
---@field prepare_command fun(self: AgentProvider, prompt: string, context: AgentContext): string[]
---@field get_available_models fun(self: AgentProvider): string[]
---@field get_default_model fun(self: AgentProvider): string
local AgentProvider = {}
AgentProvider.__index = AgentProvider

---Returns the default model identifier for this provider.
---Override in concrete implementations.
---@return string
function AgentProvider:get_default_model() error 'AgentProvider:get_default_model() is not implemented' end

---Returns the list of model identifiers this provider supports.
---Override in concrete implementations.
---@return string[]
function AgentProvider:get_available_models() error 'AgentProvider:get_available_models() is not implemented' end

---Returns the human-readable name of this provider.
---Override in concrete implementations.
---@return string
function AgentProvider:get_provider_name() error 'AgentProvider:get_provider_name() is not implemented' end

---Returns the command to run as a list of string arguments suitable for
---vim.fn.jobstart(). The first element should be the executable.
---Override in concrete implementations.
---@param prompt string         The fully-rendered prompt text.
---@param context AgentContext  Additional context for the agent.
---@return string[]
function AgentProvider:prepare_command(prompt, context) -- luacheck: ignore
  error 'AgentProvider:prepare_command() is not implemented'
end

---Creates a new AgentProvider subclass.
---Typical usage:
---
---  local MyProvider = AgentProvider:extend()
---
---  function MyProvider:get_provider_name() return 'my-provider' end
---
---  function MyProvider:get_available_models()
---    return { 'model-a', 'model-b' }
---  end
---
---  function MyProvider:prepare_command(prompt, context)
---    return { 'my-cli', '--model', context.model, '--prompt', prompt }
---  end
---
---@return AgentProvider
function AgentProvider:extend()
  local cls = setmetatable({}, { __index = self })
  cls.__index = cls
  return cls
end

---Creates a new instance of this provider.
---@return AgentProvider
function AgentProvider:new() return setmetatable({}, self) end

-- ─── Agent ────────────────────────────────────────────────────────────────────

local Logger = require 'light-ai.logging'
local Path = require 'plenary.path'

---@alias AgentStatus "idle" | "running" | "done" | "aborted" | "error"

---@class Agent
---@field num integer          Numeric identifier assigned by the caller (e.g. 1, 2, 3…).
---@field id string            Unique random run ID, used as the log file name.
---@field log Logger           Per-run logger writing to /tmp/light-ai/<id>.log
---@field temp_file string|nil Path of the output temp file for the current/last run.
---@field status AgentStatus
---@field _agent_provider AgentProvider
---@field _prompt_provider PromptProvider
---@field _job_id integer|nil  jobstart handle while running.
local Agent = {}
Agent.__index = Agent

---Creates a new Agent.
---@param num integer           Numeric identifier managed by the caller.
---@param id string             Unique run ID generated by the caller.
---@param agent_provider AgentProvider
---@param prompt_provider PromptProvider
---@return Agent
function Agent.new(num, id, agent_provider, prompt_provider)
  assert(type(id) == 'string' and id ~= '', 'Agent.new: id is required')
  local log = Logger.new(id)
  log:info('agent #%d created, provider=%s id=%s', num, agent_provider:get_provider_name(), id)
  return setmetatable({
    num = num,
    id = id,
    log = log,
    status = 'idle',
    temp_file = nil,
    _agent_provider = agent_provider,
    _prompt_provider = prompt_provider,
    _job_id = nil,
  }, Agent)
end

---Returns the path to this agent's log file.
---@return string
function Agent:log_file() return self.log.file end

---Runs the agent asynchronously.
---Falls back to provider default model when context.model is nil or empty.
---@param prompt string
---@param context AgentContext
---@param on_done fun(status: AgentStatus)  Called when job exits or is aborted.
function Agent:run(prompt, context, on_done)
  if self.status == 'running' then
    self.log:error 'run() called while already running, ignoring'
    return
  end

  -- resolve model
  if not context.model or context.model == '' then context.model = self._agent_provider:get_default_model() end

  -- resolve temp_dir to an absolute path against cwd
  context.temp_dir = Path:new(context.temp_dir):absolute()

  -- ensure temp dir exists
  vim.fn.mkdir(context.temp_dir, 'p')

  -- generate temp file paths from the agent's own id
  local tmp_file = context.temp_dir .. '/ai_' .. self.id
  local prompt_file = context.temp_dir .. '/ai_' .. self.id .. '_prompt'

  -- touch the output file so the agent can write to it
  local fh = io.open(tmp_file, 'w')
  if fh then fh:close() end

  -- write the rendered prompt to the prompt file
  local rendered = self._prompt_provider:render(prompt, {
    filename = context.filename,
    temp_file = tmp_file,
    model = context.model,
    selection = context.selection or '',
    buffer = context.buffer or '',
    range = context.range
        and string.format('range(%d:%d,%d:%d)', context.range.start_line, context.range.start_col, context.range.end_line, context.range.end_col)
      or '',
  })

  local pfh = io.open(prompt_file, 'w')
  if pfh then
    pfh:write(rendered)
    pfh:close()
  end

  self.temp_file = tmp_file
  context.temp_file = tmp_file

  self.log:info('temp_file=%s, prompt_file=%s', tmp_file, prompt_file)

  local cmd = self._agent_provider:prepare_command(rendered, context)
  self.log:info('starting job, model=%s, cmd=%s', context.model, vim.inspect(cmd))

  self.status = 'running'

  self._job_id = vim.fn.jobstart(cmd, {
    pty = true,  -- force TTY so the process doesn't buffer/suppress output
    stdout_buffered = false,

    on_stdout = function(_, data)
      for _, line in ipairs(data) do
        self.log:debug('stdout: %s', line)
        if self.status == 'running' and line:lower():find('wrote.+file.+success') then
          self.log:info 'detected success sentinel, stopping job'
          self.status = 'done'
          vim.fn.jobstop(self._job_id)
          vim.schedule(function() on_done 'done' end)
        end
      end
    end,

    on_exit = function(_, code)
      self.log:info('job exited, code=%d', code)

      -- already resolved via sentinel or abort — don't call on_done again
      if self.status == 'done' or self.status == 'aborted' then return end

      if code ~= 0 then
        self.status = 'error'
        self.log:error('job failed with exit code %d', code)
        vim.schedule(function() on_done 'error' end)
        return
      end

      self.status = 'done'
      vim.schedule(function() on_done 'done' end)
    end,
  })

  if self._job_id <= 0 then
    self.status = 'error'
    self.log:error('jobstart failed (id=%d)', self._job_id)
    vim.schedule(function() on_done 'error' end)
  end
end

---Aborts a running job. on_done will still be called with status "aborted".
function Agent:abort()
  if self.status ~= 'running' then
    self.log:debug('abort() called but status is %s, ignoring', self.status)
    return
  end
  self.log:info 'aborting job'
  self.status = 'aborted'
  if self._job_id then vim.fn.jobstop(self._job_id) end
end

return { AgentProvider = AgentProvider, Agent = Agent }
